spring:
  application:
    name: fwp-route-aggregator

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: "false"
    admin:
      fail-fast: false   # topic creation failure logs a warning but doesn't abort startup
      properties:
        connections.max.idle.ms: 540000
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 10000

routes:
  redis-key: ${ROUTES_REDIS_KEY:routes}
  cache:
    ttl: PT1M
  provider:
    one-base-url: ${PROVIDER1_BASE_URL:https://4r5rvu2fcydfzr5gymlhcsnfem0lyxoe.lambda-url.eu-central-1.on.aws/provider/flights1}
    two-base-url: ${PROVIDER2_BASE_URL:https://4r5rvu2fcydfzr5gymlhcsnfem0lyxoe.lambda-url.eu-central-1.on.aws/provider/flights2}
    connect-timeout: PT3S
    read-timeout: PT15S
    retry:
      max-attempts: 3
      wait-duration: PT0.5S

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    org.fwp: DEBUG
